import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/scss/style.scss';
import PreLoader from './components/PreLoader';

import { useRouter } from 'next/router';
export default function App({ Component, pageProps }) {
  // Preloader
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 2500);
  });

  return (
    <>
      <Head>
        <title>Majan University College</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading == true ? <PreLoader /> : <Component {...pageProps} />}
    </>
  );
}
